### ISSUE TITLE
Solo Mining for Lightbit

### ISSUE THREAD

**Issue by Nugetzrul3** [RickillerZ/cpuminer-RKZ#1]
Slight issue when solo mining on lightbit:
![Screenshot (57)](https://user-images.githubusercontent.com/52128634/69032642-129a5180-0a31-11ea-81f5-3994a04a79a1.png)

Miner just hangs? Unless it's wrong rpcport (I checked from command line options):
![Screenshot (58)_LI](https://user-images.githubusercontent.com/52128634/69032810-71f86180-0a31-11ea-9e6f-e9233faf7427.jpg)

Thanks,
Nugetzrul3

**Comment by cryptozeny** [comment]
could you try?
`--no-longpoll`

**Comment by Nugetzrul3** [comment]
> could you try?
> `--no-longpoll`

Ok actually it does work, its just that it takes a while to start-up. Anyways, I will add the `--no-longpoll`, since it makes it start-up quicker
